sudo: required
services:
  - docker
before_install:
  - docker build -t mg10445/react_test -f Dockerfile ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true mg10445/react_test npm run test -- --coverage
after_success:
  - docker build -t mh10445/multi_client ./client
  - docker build -t mh10445/multi_nginx ./nginx
  - docker build -t mh10445/multi_server ./server
  - docker build -t mh10445/multi_worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mh10445/multi_client
  - docker push mh10445/multi_nginx
  - docker push mh10445/multi_server
  - docker push mh10445/multi_worker
